-- Seed gerado de loja/data/*.ts em 2026-09-14.
-- Sao os 17 fixtures herdados da Fase 0; o catalogo real entra pelo painel.

INSERT INTO categorias (id, slug, nome, imagem, ordem, ativo) VALUES ('biquinis', 'biquinis', 'Biquínis', '', 1, 1);
INSERT INTO categorias (id, slug, nome, imagem, ordem, ativo) VALUES ('maio', 'maio', 'Maiô', '', 2, 1);

INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-tanga-sand', 'top-tanga-sand', 'Top Meia Taça + Tanga Lateral Sand', '', 'biquinis', 42800, 23800, '[]', 1, 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-tanga-sand', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-tanga-sand', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-tanga-sand', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-tanga-sand', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-triangulo-oceano', 'top-triangulo-oceano', 'Top Triângulo + Calcinha Caneleira Oceano', '', 'biquinis', 39800, 29800, '[]', 1, 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-triangulo-oceano', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-triangulo-oceano', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-triangulo-oceano', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-triangulo-oceano', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-cortininha-terracota', 'top-cortininha-terracota', 'Top Cortininha + Tanga Fio Terracota', '', 'biquinis', 37800, 26800, '[]', 1, 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cortininha-terracota', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cortininha-terracota', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cortininha-terracota', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cortininha-terracota', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-longline-marinho', 'top-longline-marinho', 'Top Longline + Calcinha Hot Pants Marinho', '', 'biquinis', 41800, 28800, '[]', 1, 4, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-longline-marinho', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-longline-marinho', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-longline-marinho', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-longline-marinho', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-frente-unica-coral', 'top-frente-unica-coral', 'Top Frente Única + Tanga Lisa Coral', '', 'biquinis', 35800, 25800, '[]', 1, 5, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-frente-unica-coral', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-frente-unica-coral', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-frente-unica-coral', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-frente-unica-coral', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-ripple-esmeralda', 'top-ripple-esmeralda', 'Top Ripple + Calcinha Caneleira Esmeralda', '', 'biquinis', 40800, 27800, '[]', 1, 6, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-ripple-esmeralda', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-ripple-esmeralda', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-ripple-esmeralda', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-ripple-esmeralda', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-cropped-lavanda', 'top-cropped-lavanda', 'Top Cropped + Tanga Fixa Lavanda', '', 'biquinis', 36800, 24800, '[]', 1, 7, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cropped-lavanda', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cropped-lavanda', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cropped-lavanda', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-cropped-lavanda', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('top-bandeau-vinho', 'top-bandeau-vinho', 'Top Bandeau + Tanga Assimétrica Vinho', '', 'biquinis', 38800, 26800, '[]', 1, 8, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-bandeau-vinho', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-bandeau-vinho', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-bandeau-vinho', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('top-bandeau-vinho', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-cutout-argola-marinho', 'maio-cutout-argola-marinho', 'Maiô Cutout Argola Marinho', '', 'maio', 15990, 14990, '[]', 1, 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-marinho', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-marinho', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-marinho', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-marinho', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-cutout-argola-off-white', 'maio-cutout-argola-off-white', 'Maiô Cutout Argola Off White', '', 'maio', 13990, 12990, '[]', 1, 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-off-white', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-off-white', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-off-white', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-cutout-argola-off-white', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-um-ombro-bicolor', 'maio-um-ombro-bicolor', 'Maiô Um Ombro Bicolor Preto e Branco', '', 'maio', 15990, 14990, '[]', 1, 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-um-ombro-bicolor', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-um-ombro-bicolor', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-um-ombro-bicolor', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-um-ombro-bicolor', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-kaftan-saia-preto', 'maio-kaftan-saia-preto', 'Maiô Kaftan + Saia Nó Preto', '', 'maio', 15990, 14990, '[]', 1, 4, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-kaftan-saia-preto', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-kaftan-saia-preto', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-kaftan-saia-preto', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-kaftan-saia-preto', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-halter-argola-natural', 'maio-halter-argola-natural', 'Maiô Halter Argola Natural', '', 'maio', 11990, 10990, '[]', 1, 5, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-halter-argola-natural', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-halter-argola-natural', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-halter-argola-natural', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-halter-argola-natural', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-colorblock-luxo-preto', 'maio-colorblock-luxo-preto', 'Maiô Colorblock Luxo Preto e Off White', '', 'maio', 15990, 14990, '[]', 1, 6, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-colorblock-luxo-preto', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-colorblock-luxo-preto', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-colorblock-luxo-preto', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-colorblock-luxo-preto', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-ana-textura-branco', 'maio-ana-textura-branco', 'Maiô Ana Textura Branco', '', 'maio', 18490, 16990, '[]', 1, 7, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-ana-textura-branco', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-ana-textura-branco', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-ana-textura-branco', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-ana-textura-branco', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-wrap-saia-champagne', 'maio-wrap-saia-champagne', 'Maiô Wrap + Saia Nó Champagne', '', 'maio', 13990, 12990, '[]', 1, 8, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-wrap-saia-champagne', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-wrap-saia-champagne', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-wrap-saia-champagne', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-wrap-saia-champagne', 'GG', 4, 1);
INSERT INTO produtos (id, slug, nome, descricao, categoria_id, preco_centavos, preco_pix_centavos, imagens, tem_kids, ordem, ativo) VALUES ('maio-bustier-set-preto', 'maio-bustier-set-preto', 'Maiô Bustiê + Calça Tule Preto', '', 'maio', 15990, 14990, '[]', 1, 9, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-bustier-set-preto', 'P', 1, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-bustier-set-preto', 'M', 2, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-bustier-set-preto', 'G', 3, 1);
INSERT INTO tamanhos (produto_id, tamanho, ordem, disponivel) VALUES ('maio-bustier-set-preto', 'GG', 4, 1);
